version: '3.3'
services:
    storagenode:
        restart: unless-stopped
        ports:
            - 'EXTERNAL_PORT_HERE:28967/tcp'
            - 'EXTERNAL_PORT_HERE:28967/udp'
            - 'DASH_BOARD_PORT_HERE:14002/tcp'
        environment:
            - 'WALLET=YOUR_WALLET_GOES_HERE'
            - 'EMAIL=YOUR_EMAIL_GOES_HERE'
            - 'ADDRESS=YOUR_IPADDRESS_GOES_HERE:EXTERNAL_PORT_HERE'
            - 'STORAGE=500GB'
            - 'SETUP=true'
        user: '1000:1000'
        volumes:
            - './identity:/app/identity'
            - './data:/app/config'
        container_name: YOUR_NODENAME_GOES_HERE
        image: 'storjlabs/storagenode:latest'
