version: '3.3'
services:
    storagenode:
        restart: unless-stopped
        ports:
            - 'EXTERNAL_PORT_HERE:28967/tcp'
            - 'EXTERNAL_PORT_HERE:28967/udp'
            - 'DASH_BOARD_PORT_HERE:14002/tcp'
        environment:
            - WALLET=0x41e1593bD5EDF1B8dBcd69d8c8E059dC8a9B4570
            - EMAIL=Example@Email.com
            - 'ADDRESS=Example_IP:Example_Port'
            - STORAGE=500GB
        user: '1000:1000'
        volumes:
            - './identity:/app/identity'
            - './data:/app/config'
        container_name: YOUR_NODENAME_GOES_HERE
        image: 'storjlabs/storagenode:latest'